### ISSUE TITLE
Help us test so we can publish publicly on Zapier

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/zapier#2]
In order to publish the app, we need to complete a validation.

The command `zapier validate` tells us what we need to do.

Mostly, we need to create Zaps for each and every trigger, action or search. That way Zapier will know that what we've built works and they will let us publish.

A free Zapier account allows you to have 3 Zaps. We have more than 3 actions, so we need multiple people to have multiple accounts so each and every trigger, search and action can be covered.

Please create some Zaps and leave them running in your account!

To get access to the private app, contact me and I'll add you.
Once the Zapier integration is published, everyone will be able to use it.

PS: There are some warnings as well that I haven't pasted here, but these can be ignored. I've already addressed them the best I can and they are not blocking.

# 1. Get your access to the app
Use this invite link: https://zapier.com/developer/public-invite/138823/2132b7099f6ec87c6474d94b4ba7e066/

# 2. Things we need to take care of:

| Category| Method | Description  | Link |
|------|-----|-----|-----|
| Publishing Tasks | triggers.InvoiceReceivedPayment | needs a successful task but doesn't have a Zap (T001)                                                      | https://platform.zapier.com/docs/integration-checks-reference#T001 |
| Publishing Tasks | triggers.InvoiceReceivedPayment | need to compare static sample with latest task but doesn't have a Zap (T004)                               | https://platform.zapier.com/docs/integration-checks-reference#T004 |
| Publishing Tasks | triggers.InvoiceReceivedPayment | need to compare a live trigger result with output field definition but doesn't have a Zap (T005)           | https://platform.zapier.com/docs/integration-checks-reference#T005 |
| Publishing Tasks | triggers.InvoiceReceivedPayment | need to compare polling sample with latest task but doesn't have a Zap (T006)                              | https://platform.zapier.com/docs/integration-checks-reference#T006 |
| Publishing Tasks | triggers.InvoiceReceivedPayment | need to compare a polling sample with output field definition but doesn't have a Zap (Z001)                | https://platform.zapier.com/docs/integration-checks-reference#Z001 |
| Publishing Tasks | triggers.InvoicePaidInFull      | needs a successful task but doesn't have a Zap (T001)                                                      | https://platform.zapier.com/docs/integration-checks-reference#T001 |
| Publishing Tasks | triggers.InvoicePaidInFull      | need to compare static sample with latest task but doesn't have a Zap (T004)                               | https://platform.zapier.com/docs/integration-checks-reference#T004 |
| Publishing Tasks | triggers.InvoicePaidInFull      | need to compare a live trigger result with output field definition but doesn't have a Zap (T005)           | https://platform.zapier.com/docs/integration-checks-reference#T005 |
| Publishing Tasks | triggers.InvoicePaidInFull      | need to compare polling sample with latest task but doesn't have a Zap (T006)                              | https://platform.zapier.com/docs/integration-checks-reference#T006 |
| Publishing Tasks | triggers.InvoicePaidInFull      | need to compare a polling sample with output field definition but doesn't have a Zap (Z001)                | https://platform.zapier.com/docs/integration-checks-reference#Z001 |
| Publishing Tasks | search.FindInvoice              | needs a successful task but doesn't have a Zap (T001)                                                      | https://platform.zapier.com/docs/integration-checks-reference#T001 |
| Publishing Tasks | meta.stats                      | must have at least 3 users with live Zaps, currently has 1 (S001)                                          | https://platform.zapier.com/docs/integration-checks-reference#S001 |
| Publishing Tasks | meta.stats                      | trigger "InvoiceConfirmed" has no live Zaps using it, must have at least one (S002)                        | https://platform.zapier.com/docs/integration-checks-reference#S002 |
| Publishing Tasks | meta.stats                      | trigger "InvoicePaidInFull" has no live Zaps using it, must have at least one (S002)                       | https://platform.zapier.com/docs/integration-checks-reference#S002 |
| Publishing Tasks | meta.stats                      | trigger "InvoiceReceivedPayment" has no live Zaps using it, must have at least one (S002)                  | https://platform.zapier.com/docs/integration-checks-reference#S002 |
| Publishing Tasks | meta.stats                      | search "FindInvoice" has no live Zaps using it, must have at least one (S002)                              | https://platform.zapier.com/docs/integration-checks-reference#S002 |

**Comment by leoserpa14** [comment]
I want to test it using Glide + Zapier. But I'm just now starting to learn about this. Seems simple enough to follow the tutorials but I have 1 very important question: Does this integration with Zapier supports BTC Pay Server Lightning functionalities?

**Comment by woutersamaey** [comment]
There are events for when an invoice is created, paid etc, and that works for both onchain and LN.

**Comment by woutersamaey** [comment]
Testing has finished and the app is now available to all as a public beta.
